### ISSUE TITLE
R ladies Lyon chapter to be added to github to create meetup_presentations_lyon folder

### ISSUE THREAD

**Issue by hlennon** [rladies/starter-kit#131]
I would like to upload our R ladies Lyon meetings events and slides to the R Ladies global added to github to create meetup_presentations_lyon folder

Perhaps I have misunderstood the instructions for the setup
"Contact any of the admins (e.g. @hannah) of the GitHub organisation to be added as a member."

@hannah, @TanjaKec can you grant me access?

Thanks in advance
Hannah

**Comment by hfrick** [comment]
Hi Hannah, thanks for reaching out. Are you one of the Lyon organisers or a presenter at the meetup?

**Comment by hlennon** [comment]
Hi Hannah,

One of the organisers - I should have probably emailed from the rladies email, cc’d now.

Thanks
Hannah

**Comment by hfrick** [comment]
@hlennon I've sent you an invitation to join the github org so that you can access https://github.com/rladies/meetup-presentations_lyon

**Comment by hlennon** [comment]
Thanks Hannah
