### ISSUE TITLE
add info on how to update chapter contacts in "retiring a chapter" section of starter kit

### ISSUE THREAD

**Issue by sheilasaia** [rladies/starter-kit#144]
add language to the "retiring a chapter" section of the starter kit to communicate how a chapter organizer can update contact information should they be passing along the chapter to someone new.

**Comment by cvitolo** [comment]
Hi @sheilasaia , thanks for offering to help. Let me know if I can do anything to help.

**Comment by maelle** [comment]
@sheilasaia could you please clarify what's needed here?

**Comment by sheilasaia** [comment]
@maelle I will try to close this this weekend. Sorry it's taken so long!

**Comment by maelle** [comment]
np!!

**Comment by sheilasaia** [comment]
@maelle, text to change is below:

```
Things to try if you are struggling or can no longer serve as your chapter's organiser:

1. If you struggle to organise events, please let us know and we will put you in contact with an experienced organiser that can mentor you.
2. Please message the members of your chapter on meetup and ask if anyone is willing to help you co-organise the chapter or take over the chapter.
  - If someone comes forward, send an email info@rladies.org to inform them of this change and share the new contact's information. Next, check that the current-chapters.csv in the starter kit here reflects this change by sending R-Ladies a GitHub pull request with the updated information. If you do not feel comfortable making a pull request, please mention this in your initial email to info@rladies.org. We will help you update the contact information for the chapter. The new contact will also receive access to the organiser Slack channel.
  - If no one comes forward, please make an announcement in the community slack to see if anyone is willing to take over.
```

**Comment by yabellini** [comment]
In the first point we can add a link to mentorship program? There is a form I think. Maybe Flor and Nad can add something about that?

**Comment by maelle** [comment]
thanks @sheilasaia ! I'll incorporate the change next week.

@yabillini in the new guide I added the guidance about the program https://r-ladies-guide.netlify.app/coordination/mentoring/ That's a good point in any case: once I have more content in the guide I will add more cross-references (because we can't be sure everyone will read the book "cover to cover")

**Comment by maelle** [comment]
Thank you both, https://r-ladies-guide.netlify.app/organization/intro/retiring/ now has more info.

If you have any further idea/feedback please open an issue in https://github.com/rladies/rladiesguide
