### ISSUE TITLE
Instructions for Stickermule need to be updated

### ISSUE THREAD

**Issue by angela-li** [rladies/starter-kit#145]
From recent experience, you can now simply upload the [hex-logo-with-text.png](https://github.com/rladies/starter-kit/blob/master/stickers/hex-logo-with-text.png) file, and they'll process it correctly (aka they don't need a bleed anymore). It would be great to revise the sticker instructions to reflect this!

**Comment by cvitolo** [comment]
Hi @angela-li , thanks for the suggestion. Can I assign you to this issue?

**Comment by maelle** [comment]
Duplicate of https://github.com/rladies/rladiesguide/issues/13
