### ISSUE TITLE
add twitter user to R-Ladies Mendoza

### ISSUE THREAD

**Issue by anadiedrichs** [rladies/starter-kit#17]
The twitter user for R-Ladies Mendoza chapter is https://twitter.com/RLadiesMza.

Thanks.

Ana

**Comment by gdequeiroz** [comment]
Thank you @anadiedrichs! Just added it.

**Comment by gdequeiroz** [comment]
https://github.com/rladies/starter-kit/commit/a2317ac014cfd3d2c2ff9476a56af114b7e7f807
