### ISSUE TITLE
Remote chapter is missing

### ISSUE THREAD

**Issue by cvitolo** [rladies/starter-kit#184]
@lauracion noticed the remote chapter is missing. All the info need to be added back.

**Comment by cvitolo** [comment]
I added back remote, @lauracion @yabellini could you please check if the info is correct and complete?Do we have the slack link?

**Comment by cvitolo** [comment]
Found slack link, anything else missing?

**Comment by yabellini** [comment]
Auriel is the only organizer??

**Comment by yabellini** [comment]
![IMG_20191230_164219](https://user-images.githubusercontent.com/2473676/71597836-7f6e3480-2b23-11ea-9205-6b11dc547347.jpg)
We use this info in March 2019

**Comment by cvitolo** [comment]
I was wondering the same... Auriel is the only one listed on meetup.com as co-organiser. But well done on finding the full list! I just added all the other names. Thank you so much @yabellini . Shall we close this or there is anything missing?

**Comment by yabellini** [comment]
I think is ready! We can close
