### ISSUE TITLE
Can't find the Code of conduct in Portuguese

### ISSUE THREAD

**Issue by beatrizmilz** [rladies/starter-kit#235]
Hello! The translation of the Code of Conduct to Portuguese used to be in the wiki in this link: https://github.com/rladies/starter-kit/wiki/Code-of-Conduct

Now this page redirects to a new page (which is not the code of conduct): https://guide.rladies.org/

I navigated in the webpage and found the CC page https://guide.rladies.org/about/coc/ , which refers to another link: https://rladies.org/code-of-conduct/ which haves the CC only in English. In the end of the page there is a link to Portuguese and Spanish (https://github.com/rladies/starter-kit/wiki/Code-of-Conduct#portuguese ) but the code of conduct has been removed 

Can someone point me to where the translated code of conducts are? @yabellini @maelle 

Thank you! The CC in Portuguese is really important for us.

**Comment by beatrizmilz** [comment]
https://github.com/rladies/starter-kit/wiki/Code-of-Conduct/d41ffc0fb9b8da55413686011e8a27146a9d40a1 in the history of the wiki I was able to see it, but aparently it was removed

**Comment by maelle** [comment]
@beatrizmilz yes sorry now the COC is at https://github.com/rladies/.github/blob/master/CODE_OF_CONDUCT.md#portuguese because this way the file applies by default to all repositories in the organization. I have updated the wiki and will add the link to the guide. I am sorry!

**Comment by maelle** [comment]
Now https://guide.rladies.org/about/coc/ is updated. Thanks and sorry again!

**Comment by beatrizmilz** [comment]
Hi @maelle ! There is no need to say sorry, thanks so much for the links! I'll update them in our meetup page :)
