### ISSUE TITLE
find new homes for remaining files

### ISSUE THREAD

**Issue by drmowinckels** [rladies/starter-kit#274]
The starter-kit is nor surpassed bu the organisational guide, and much of its content has already been moved to new homes. 
The remaining content should also find new homes, so we can archive this repo.

- [x]  The ES folder contains some rules&guidelines in both English and Spanish, and these should likely be present in some form on either the website or the organisational guide.
- [ ] The ROCUR folder contains materials to create ROCUR twitter cards en announcements etc. Are these needed here or do they exist other places?

**Comment by drmowinckels** [comment]
gonna tag some people that might have ideas about of some of this is contained somewhere else also, or might have an idea of where to place tings.

@maelle , @yabellini , @shannonpileggi  🙏🏼

**Comment by yabellini** [comment]
I can check if the Spanish version of these files is in some other place.  If not, I can save them until we find a home in Spanish ;-).

**Comment by yabellini** [comment]
It was my first translation for a community. These files have sentimental value for me <3.

**Comment by drmowinckels** [comment]
The text in english is at least not in the website, I'll have a peak at the guide and see if its there. I dont know if we would ever consider also translating the guide? Its a lot of job to maintain in several languages, but would of course be great for our organisers it it was. 

Ok, so the mission text at least is in English in the guide:
https://guide.rladies.org/about/mission/

so, I think we could consider adding it to the guide repo, as an es.md, in preparation for a possible translation? @maelle likely has _opinions_ about this 🙃 

I'm now wondering if the Rules and Guidelines are like a first iteration of our CoC? Can that be correct?

**Comment by yabellini** [comment]
Not only the CoC. What it contained was the structure, mission, vision, and how we are organized.  It also had some details about social networks and then the CoC.

**Comment by yabellini** [comment]
I download both files, so I have them.  This probably is also not updated and old.  So, in my case, checking that the Spanish stuff is done is okay.

**Comment by drmowinckels** [comment]
rocur data has now been moved to the [rocur repo](https://github.com/rladies/rocur). All files have new homes, and I will archive this repo.
