### ISSUE TITLE
Put together R-Ladies organizer bookdown

### ISSUE THREAD

**Issue by angela-li** [rladies/starter-kit#48]
I'm interested in putting together a resource specifically for Meetup organizers that goes over some of the following material:

- How to organize effective events
- How to spread the word about your Meetup
- How to get sponsors (and swag) for your Meetup
- How to recruit and support co-organizers
- Tricky issues: some perspectives on allowing men to come + teaching effective allyship
- How to build a community that runs itself!

We have resources about starting chapters, but nothing about how to effectively run and organize a chapter once you've started one! I would love to put things that I've learned in the process of starting a Meetup in one place and share it with future organizers.

I'm envisioning this as a resource that would allow women, some of whom may never have organized a community group before, to build their confidence in their R-Ladies organizing.

**Comment by gdequeiroz** [comment]
This is a great idea @angela-li! We need this.

**Comment by angela-li** [comment]
Great! I'll start a new repo in the R-Ladies Github called `organizer-guide` and write up a few topics that I'd like to cover. I'll start with a few that I think are important (the above mentioned), and I'll add more over time.

**Comment by gdequeiroz** [comment]
Perfect!

**Comment by angela-li** [comment]
Voila, the [new repo](https://github.com/rladies/organizer-guide/blob/master/README.md). I'll add over the next few weeks! I also plan to have some 1-on-1 conversations with organizers to get a sense of questions they have in starting a group as I build out this resource.
